name: movieflix
description: app about movies
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  floor: ^1.4.2
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.2
  injectable_generator: ^2.1.6
  shared_preferences: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.5
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
