name: movieflix
description: app about movies
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  dio: ^5.2.1
  pretty_dio_logger: ^1.3.1
  floor: ^1.4.2
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.2
  json_serializable: ^6.7.0
  retrofit: ^4.0.1
  shared_preferences: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.5
  floor_generator: ^1.4.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
