name: movieflix
description: app about movies
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ./data
  di:
    path: ./di
  repository: 
    path: ./repository
  get_it: ^7.6.0
  injectable: ^2.1.2
  logger: ^1.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.5

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
