name: domain
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.domain
    iosBundleIdentifier: com.example.domain
