name: di
version: 1.0.0+1
puplish_to: none

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  injectable: ^2.1.2
  dio: ^5.2.1
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.2
  data:
    path: ../data
  repository:
    path: ../repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.6
  build_runner: ^2.4.5

flutter:
  module:
    androidX: true
    androidPackage: com.example.di
    iosBundleIdentifier: com.example.di
